@echo on
"C:\VulkanSDK\1.3.296.0\Bin\glslc.exe" %1"\shaders\basic_triangle_shader.vert" -o %2"\shaders\vert.spv"
"C:\VulkanSDK\1.3.296.0\Bin\glslc.exe" %1"\shaders\depth_prepass.frag" -o %2"\shaders\prepass.spv"
"C:\VulkanSDK\1.3.296.0\Bin\glslc.exe" %1"\shaders\basic_fragment_shader.frag" -o %2"\shaders\frag.spv"
"C:\VulkanSDK\1.3.296.0\Bin\glslc.exe" %1"\shaders\quad_shader.vert" -o %2"\shaders\quad.spv"
"C:\VulkanSDK\1.3.296.0\Bin\glslc.exe" %1"\shaders\gbuffer_generation.frag" -o %2"\shaders\gbuffergen.spv"
"C:\VulkanSDK\1.3.296.0\Bin\glslc.exe" %1"\shaders\gbuffer_generation.vert" -o %2"\shaders\gbuffergen_vert.spv"
"C:\VulkanSDK\1.3.296.0\Bin\glslc.exe" %1"\shaders\lighting.frag" -o %2"\shaders\lighting_frag.spv"
"C:\VulkanSDK\1.3.296.0\Bin\glslc.exe" %1"\shaders\blit.frag" -o %2"\shaders\blit_frag.spv"
"C:\VulkanSDK\1.3.296.0\Bin\glslc.exe" %1"\shaders\cubemap.vert" -o %2"\shaders\cubemap_vert.spv"
"C:\VulkanSDK\1.3.296.0\Bin\glslc.exe" %1"\shaders\environment.frag" -o %2"\shaders\environment.spv"
"C:\VulkanSDK\1.3.296.0\Bin\glslc.exe" %1"\shaders\diffuse_irradiance.frag" -o %2"\shaders\irradiance.spv"
"C:\VulkanSDK\1.3.296.0\Bin\glslc.exe" %1"\shaders\shadow_prepass.vert" -o %2"\shaders\shadow_prepass_vert.spv"
"C:\VulkanSDK\1.3.296.0\Bin\glslc.exe" %1"\shaders\shadow_prepass.frag" -o %2"\shaders\shadow_prepass_frag.spv"
